name: Build & Push Docker Images

# Trigger on every push to main
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - uses: actions/checkout@v4

      # 2. Log in to ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # 3. Build & push the backend image
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY }}/backend:latest ./backend
          docker push ${{ secrets.AZURE_REGISTRY }}/backend:latest

      # 4. Build & push the frontend image
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY }}/frontend:latest ./frontend
          docker push ${{ secrets.AZURE_REGISTRY }}/frontend:latest
